export const TASK_TYPES = {
  // FETCH
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAIL: 'FETCH_FAIL',

  // ADD
  ADD_REQUEST: 'ADD_REQUEST',
  ADD_SUCCESS: 'ADD_SUCCESS',
  ADD_FAIL: 'ADD_FAIL',

  // UPDATE
  UPDATE_REQUEST: 'UPDATE_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  UPDATE_FAIL: 'UPDATE_FAIL',

  // DELETE
  DELETE_REQUEST: 'DELETE_REQUEST',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  DELETE_FAIL: 'DELETE_FAIL',

  // CLEAR
  CLEAR_REQUEST: 'CLEAR_REQUEST',
  CLEAR_SUCCESS: 'CLEAR_SUCCESS',
  CLEAR_FAIL: 'CLEAR_FAIL',
};
